xone-wired-y := transport/wired.o
xone-dongle-y := transport/dongle.o transport/mt76.o
xone-gip-bus-y := bus/bus.o bus/protocol.o auth/auth.o auth/crypto.o
xone-gip-gamepad-y := driver/gamepad.o driver/common.o
xone-gip-headset-y := driver/headset.o
xone-gip-chatpad-y := driver/chatpad.o
xone-gip-madcatz_glam-y := driver/madcatz_glam.o
xone-gip-madcatz_strat-y := driver/madcatz_strat.o
xone-gip-pdp_jaguar-y := driver/pdp_jaguar.o

obj-$(CONFIG_JOYSTICK_XONE) := xone-wired.o xone-dongle.o xone-gip-bus.o xone-gip-gamepad.o xone-gip-headset.o xone-gip-chatpad.o xone-gip-madcatz_glam.o xone-gip-madcatz_strat.o xone-gip-pdp_jaguar.o

