#ifndef CLK_MISTER_OCRAM_H
#define CLK_MISTER_OCRAM_H

#define MISTER_CTX_OFFSET	2048
#define MISTER_TARGET_NUMER	0
#define MISTER_TARGET_MPU	4
#define MISTER_TARGET_MAIN	8
#define MISTER_TARGET_USER	12
#define MISTER_FLASH_GATES	16
#define MISTER_STAGE		20
#define MISTER_ERROR		24
#define MISTER_OLD_MPU		32
#define MISTER_OLD_MAIN		36
#define MISTER_OLD_DBG		40
#define MISTER_OLD_USER		44

#endif
