obj-$(CONFIG_AIC_LOADFW_SUPPORT) += aic_load_fw/
obj-$(CONFIG_AIC8800_WLAN_SUPPORT) += aic8800_fdrv/
obj-$(CONFIG_AIC_ZLP_QUIRK) += aic_zlp_quirk/

# Driver-private options used by the existing source.
CONFIG_USE_FW_REQUEST := n
CONFIG_PREALLOC_RX_SKB := y
CONFIG_PREALLOC_TXQ := y
CONFIG_WOWLAN := n

